### ISSUE TITLE
Basic Form Styling

### ISSUE THREAD

**Issue by seveibar** [rpiml/okcollege-web-client#4]

**Comment by hodgka** [comment]
The form.json file lists several components thus far (slider, multi-choice, choice), but I think we would benefit having a few more "components" to deal with tricky things like having a huge list of sports, with a couple common ones, or having SAT/SAT2 scores where you have a specific score associated with a value.

A couple components(they're really just combinations of other components) I'm proposing are:

1). Text-boxes where you can have a free form response for any "why?" question.

2). A multi-choice component with a drop down menu(for sports) i.e. have a list of the top 3 most common (football, track and field, basketball), and then a drop down menu with other sports 

3). Multi-column text-boxes( for SAT/ACT and SAT2) i.e. 3 text-boxes  for 3 sat scores, 5 text-boxes for act, 2 columns where you can add rows for the SAT2 test name and score.

**Comment by hodgka** [comment]
Another form styling proposal is having the option to expand a choice/multi-choice into some other component or have some basic "logic flow." 
i.e.
 Do you have any notable awards? 
[ ] Yes
[ ] No

... becomes ...

  Do you have any notable awards? 
[x ] Yes
    Please list them below
    [Textbox]
[ ] No


Also if we have some way to control "logic flow" through the survey, then we could serve a version of the survey specific to college students vs high school students vs college grads so we can ask more relevant questions and have a better ux with the survey.

**Comment by hodgka** [comment]
Resolution:

1). Why questions - Not necessary. Why questions can come later/ for survey improvement/ for reinforcing our hypotheses.
2). Sports - Nest a drop down component inside a multichoice component.
3). SAT/SAT2 Multicolumn textboxes - Just use drop down menus with scores/ drop down menu with test name and score

"logic flow" isn't necessary for the MVP.

**Comment by jowlee** [comment]
Completed in #9
